version: 3
tasks:
    generate:
        desc: generating http handlers && m
        sources:
            - api/simple-app.yaml
            - internal/simple-app/domain/interfaces.go
        generates:
            - internal/simple-app/driver/openapi_gen.go
            - internal/simple-app/domain/mocks/*.go
        cmds:
            - go generate ./...
    test:
        desc: running tests
        dir: "internal/"
        deps:
            - generate
        cmds:
            - go test -cover -race -v ./...
    lint:
        desc: running linter
        deps:
            - generate
        dir: "internal/"
        cmds:
            - golangci-lint run
    run:
        desc: deploy app to acorn
        deps:
            - generate
        cmds:
            - acorn run -n simple-app
    dev:
        desc: deploy app to acorn in dev-mod
        deps:
            - generate
        cmds:
            - acorn dev -n simple-app
    stop:
        desc: stop app in acorn
        cmds:
            - acorn stop simple-app
    logs:
        desc: show logs in acorn
        cmds:
            - acorn logs -n simple-app
    rm:
        desc: show logs in acorn
        cmds:
            - acorn rm -n simple-app